# Generated by Django 6.0.6 on 2026-06-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personagem', models.CharField(max_length=100)),
                ('nome_jogador', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('vida', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('forca', models.IntegerField()),
                ('destreza', models.IntegerField()),
                ('inteligencia', models.IntegerField()),
                ('sabedoria', models.IntegerField()),
                ('carisma', models.IntegerField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
    ]
