# Generated by Django 6.0.6 on 2026-06-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='constituicao',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
